
import type { Product, Sale } from '@/lib/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'product.rice.name',
    description: 'product.rice.description',
    price: 150,
    stock: 50,
    lowStockThreshold: 10,
    category: 'Grains',
    imageUrl: 'https://images.unsplash.com/photo-1627482265910-5c0ff6bee088?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8YmFnJTIwcmljZXxlbnwwfHx8fDE3NjE2NDc4MTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_2',
    name: 'product.lentils.name',
    description: 'product.lentils.description',
    price: 120,
    stock: 45,
    lowStockThreshold: 15,
    category: 'Lentils',
    imageUrl: 'https://images.unsplash.com/photo-1587041770006-965fc1251180?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxsZW50aWxzJTIwZGFsfGVufDB8fHx8MTc2MTY0NzgxN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_3',
    name: 'product.flour.name',
    description: 'product.flour.description',
    price: 50,
    stock: 80,
    lowStockThreshold: 20,
    category: 'Flour',
    imageUrl: 'https://images.unsplash.com/photo-1710857389305-5cba9211033f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxmbG91ciUyMGJhZ3xlbnwwfHx8fDE3NjE1NzUxNTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_4',
    name: 'product.oil.name',
    description: 'product.oil.description',
    price: 180,
    stock: 30,
    lowStockThreshold: 10,
    category: 'Oils',
    imageUrl: 'https://images.unsplash.com/photo-1720468750623-39e9a09f5067?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjb29raW5nJTIwb2lsfGVufDB8fHx8MTc2MTY0NzgxNnww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'liter',
  },
  {
    id: 'prod_5',
    name: 'product.turmeric.name',
    description: 'product.turmeric.description',
    price: 40,
    stock: 100,
    lowStockThreshold: 30,
    category: 'Spices',
    imageUrl: 'https://images.unsplash.com/photo-1698943510650-9232c98a5328?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx0dXJtZXJpYyUyMHBvd2RlcnxlbnwwfHx8fDE3NjE2NDMxNzV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: '100g',
  },
  {
    id: 'prod_6',
    name: 'product.cumin.name',
    description: 'product.cumin.description',
    price: 60,
    stock: 70,
    lowStockThreshold: 25,
    category: 'Spices',
    imageUrl: 'https://images.unsplash.com/photo-1731970820339-e725b78f55e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxjdW1pbiUyMHNlZWRzfGVufDB8fHx8MTc2MTU1ODYxOHww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: '100g',
  },
  {
    id: 'prod_7',
    name: 'product.sugar.name',
    description: 'product.sugar.description',
    price: 45,
    stock: 120,
    lowStockThreshold: 40,
    category: 'Sweeteners',
    imageUrl: 'https://images.unsplash.com/photo-1761426079132-c2c9978b9514?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxzdWdhciUyMHBhY2tldHxlbnwwfHx8fDE3NjE2NDc4MTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_8',
    name: 'product.tea.name',
    description: 'product.tea.description',
    price: 250,
    stock: 40,
    lowStockThreshold: 10,
    category: 'Beverages',
    imageUrl: 'https://images.unsplash.com/photo-1597481288323-efff1b2f6d23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0ZWElMjBib3h8ZW58MHx8fHwxNzYxNTc1MTUxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: '250g',
  },
  {
    id: 'prod_9',
    name: 'product.ghee.name',
    description: 'product.ghee.description',
    price: 550,
    stock: 25,
    lowStockThreshold: 5,
    category: 'Dairy',
    imageUrl: 'https://images.unsplash.com/photo-1543463573-35e4afd0ab43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxnaGVlJTIwamFyfGVufDB8fHx8MTc2MTU3NTE1MXww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: '500ml',
  },
  {
    id: 'prod_10',
    name: 'product.onions.name',
    description: 'product.onions.description',
    price: 30,
    stock: 90,
    lowStockThreshold: 20,
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1741517481122-51d958803203?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxmcmVzaCUyMG9uaW9uc3xlbnwwfHx8fDE3NjE1NTkyODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_11',
    name: 'product.potatoes.name',
    description: 'product.potatoes.description',
    price: 25,
    stock: 150,
    lowStockThreshold: 30,
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1594885270227-c61f9bc1383d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMHBvdGF0b2VzfGVufDB8fHx8MTc2MTY0NzgxN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_12',
    name: 'product.tomatoes.name',
    description: 'product.tomatoes.description',
    price: 40,
    stock: 60,
    lowStockThreshold: 15,
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1683009118690-a5851ccb1112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxmcmVzaCUyMHRvbWF0b2VzfGVufDB8fHx8MTc2MTU5NDQ1MXww&ixlib=rb-4.1.0&q=80&w=1080',
    unit: 'kg',
  },
  {
    id: 'prod_13',
    name: 'product.biscuits.name',
    description: 'product.biscuits.description',
    price: 50,
    stock: 200,
    lowStockThreshold: 50,
    category: 'Snacks',
    imageUrl: 'https://picsum.photos/seed/biscuit/400/300',
    unit: 'pack',
  },
  {
    id: 'prod_14',
    name: 'product.chips.name',
    description: 'product.chips.description',
    price: 20,
    stock: 150,
    lowStockThreshold: 40,
    category: 'Snacks',
    imageUrl: 'https://picsum.photos/seed/chips/400/300',
    unit: 'pack',
  },
  {
    id: 'prod_15',
    name: 'product.cola.name',
    description: 'product.cola.description',
    price: 40,
    stock: 100,
    lowStockThreshold: 25,
    category: 'Beverages',
    imageUrl: 'https://picsum.photos/seed/cola/400/300',
    unit: 'bottle',
  },
  {
    id: 'prod_16',
    name: 'product.chocolate.name',
    description: 'product.chocolate.description',
    price: 45,
    stock: 180,
    lowStockThreshold: 60,
    category: 'Chocolates',
    imageUrl: 'https://picsum.photos/seed/chocolate/400/300',
    unit: 'piece',
  }
];


export const MOCK_SALES: Sale[] = [
    {
      id: "sale_1",
      date: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
      items: [{ productId: "prod_1", quantity: 2, priceAtSale: 150 }, { productId: "prod_3", quantity: 1, priceAtSale: 50 }],
      total: 350
    },
    {
      id: "sale_2",
      date: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
      items: [{ productId: "prod_10", quantity: 5, priceAtSale: 30 }, { productId: "prod_11", quantity: 5, priceAtSale: 25 }],
      total: 275
    },
    {
      id: "sale_3",
      date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
      items: [{ productId: "prod_2", quantity: 3, priceAtSale: 120 }, { productId: "prod_5", quantity: 2, priceAtSale: 40 }],
      total: 440
    },
    {
      id: "sale_4",
      date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
      items: [{ productId: "prod_8", quantity: 1, priceAtSale: 250 }, { productId: "prod_7", quantity: 2, priceAtSale: 45 }],
      total: 340
    },
    {
      id: "sale_5",
      date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
      items: [{ productId: "prod_1", quantity: 1, priceAtSale: 150 }, { productId: "prod_11", quantity: 10, priceAtSale: 25 }],
      total: 400
    },
    {
      id: "sale_6",
      date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
      items: [{ productId: "prod_4", quantity: 1, priceAtSale: 180 }, { productId: "prod_9", quantity: 1, priceAtSale: 550 }],
      total: 730
    },
     {
      id: "sale_7",
      date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
      items: [{ productId: "prod_12", quantity: 3, priceAtSale: 40 }, { productId: "prod_6", quantity: 1, priceAtSale: 60 }],
      total: 180
    }
  ];
  

    